# SPDX-License-Identifier: MIT
#
# This file may contain content generated or assisted by Artificial
# Intelligence tools and subsequently reviewed and modified by human
# contributors. See AI_DISCLAIMER.md for licensing terms and additional AI
# disclosures.

# -----------------------------------------------------------------------------
# Release automation. This repository has no build beyond `docker build`, so
# this Makefile exists for one purpose: to cut a release without anyone having
# to work out the next version number by hand.
#
# WHERE THE VERSION COMES FROM: the VERSION file. It is also what
# build-verify.yml stamps into the image's OCI label and what build-deploy.yml
# tags the published image with, so it stays the single source of truth
# instead of drifting from a tag.
#
# The bump targets deliberately stop at the local annotated tag. Pushing is a
# separate, explicit `release-push`, so a mistyped level or a bad changelog
# roll is recoverable with `git tag -d` + `git reset --hard HEAD~1` and never
# escapes the machine.
#
# Portability: no GNU coreutils on macOS. Bump arithmetic is POSIX
# `$$((...))` over an `IFS=. read`, not `seq`/`bc`. The changelog is rewritten
# through `awk` into a temp file and `mv`d, never `sed -i` -- BSD `sed -i`
# demands a backup suffix and GNU `sed -i` refuses one, so no single `sed -i`
# invocation works on both this laptop and an ubuntu runner.
#
# Every awk program is kept on ONE physical line. A `\`-continuation inside a
# single-quoted awk program would be passed to the shell literally and awk
# would choke on it.
#
# Initial version generated by an AI assistant and reviewed/approved by
# Rubens Gomes.
#
# @author Rubens Gomes
# -----------------------------------------------------------------------------

.DEFAULT_GOAL := help

VERSION     := $(shell cat VERSION 2>/dev/null)
RELEASE_TAG := v$(VERSION)

# Preflight shared by every release target. Read-only: verifies the repo is
# in a fit state to be tagged and exits non-zero otherwise. Deliberately does
# NOT fail on untracked files -- `.idea/`-style noise is not a reason to
# block a release.
#
# The origin sync check compares against FETCH_HEAD rather than
# `refs/remotes/origin/main`, because `git fetch origin main` does not
# reliably update the remote-tracking ref on every git version. A fetch
# failure is a WARNING, not an error, so the release targets still work
# offline.
define RELEASE_PRECHECK
echo "=== RELEASE PRECHECK ==="; \
if [ ! -f VERSION ]; then \
  echo "ERROR: VERSION file is missing at the repo root." >&2; exit 1; \
fi; \
_v=$$(cat VERSION); \
case "$$_v" in \
  [0-9]*.[0-9]*.[0-9]*) ;; \
  *) echo "ERROR: VERSION '$$_v' is not MAJOR.MINOR.PATCH." >&2; exit 1;; \
esac; \
case "$$_v" in \
  *[!0-9.]*|*.*.*.*|*..*|.*|*.) \
    echo "ERROR: VERSION '$$_v' is not MAJOR.MINOR.PATCH." >&2; exit 1;; \
esac; \
if ! git diff --quiet || ! git diff --cached --quiet; then \
  echo "ERROR: working tree is dirty. Commit or stash before releasing." >&2; \
  git status --short >&2; \
  exit 1; \
fi; \
_br=$$(git rev-parse --abbrev-ref HEAD); \
if [ "$$_br" != "main" ]; then \
  echo "ERROR: releases are cut from main, not '$$_br'." >&2; \
  echo "  This repo is trunk-based: all work lands on main directly, and a" >&2; \
  echo "  release is a bump + tag on main. See make release-check." >&2; \
  exit 1; \
fi; \
if git fetch --quiet origin main 2>/dev/null; then \
  if ! git merge-base --is-ancestor FETCH_HEAD HEAD; then \
    echo "ERROR: HEAD does not contain origin/main." >&2; \
    echo "  Pull main before releasing." >&2; \
    exit 1; \
  fi; \
else \
  echo "  WARN: could not fetch origin, skipping the sync check"; \
fi; \
echo "  ok: VERSION=$$_v, branch=$$_br, tree clean"
endef

# A bump with an empty [Unreleased] section produces a release note that says
# nothing, which is worse than no release at all. Counts `- ` bullets between
# the [Unreleased] heading and the next version heading.
#
# Anchoring on the full `^## \[` (hash, hash, SPACE, bracket) matters -- the
# prose at the top of CHANGELOG.md mentions `[Unreleased]` inline, and a
# looser pattern either misses the real heading or matches the prose.
define RELEASE_REQUIRE_UNRELEASED
_n=$$(awk '/^## \[Unreleased\]/{f=1;next} f && /^## \[[0-9]/{exit} f && /^- /{c++} END{print c+0}' CHANGELOG.md); \
if [ "$$_n" -eq 0 ]; then \
  echo "ERROR: CHANGELOG.md [Unreleased] has no entries - nothing to release." >&2; \
  exit 1; \
fi; \
echo "  ok: $$_n changelog entrie(s) under [Unreleased]"
endef

# Creates the annotated tag for whatever VERSION currently holds. Re-reads the
# file rather than using $(VERSION), because RELEASE_BUMP rewrites VERSION
# after make has already expanded its variables.
define RELEASE_TAG_BODY
_v=$$(cat VERSION); \
_tag="v$$_v"; \
if git rev-parse -q --verify "refs/tags/$$_tag" >/dev/null; then \
  echo "ERROR: tag $$_tag already exists." >&2; exit 1; \
fi; \
git tag -a "$$_tag" -m "Release $$_tag"; \
echo "=== TAGGED $$_tag ==="; \
echo "  nothing has been pushed. Inspect with 'git show --stat HEAD', then:"; \
echo "    make release-push     push main + $$_tag (this publishes the release)"; \
echo "  or undo with:"; \
echo "    git tag -d $$_tag && git reset --hard HEAD~1"; \
echo "  (nothing has left this machine until 'make release-push'.)"
endef

# The bump itself. LEVEL (patch|minor|major) comes from the calling recipe.
# Order matters: every check that can fail runs BEFORE the first write, so a
# rejected release leaves the tree exactly as it found it.
#
# The changelog roll replaces the `## [Unreleased]` heading with a fresh
# empty [Unreleased] block followed by the new version heading. The old
# Unreleased body is left in place and therefore falls under the new
# version -- which is precisely the Keep a Changelog promotion.
define RELEASE_BUMP
$(RELEASE_PRECHECK); \
$(RELEASE_REQUIRE_UNRELEASED); \
IFS=. read -r _ma _mi _pa < VERSION; \
case "$$LEVEL" in \
  major) _ma=$$((_ma + 1)); _mi=0; _pa=0;; \
  minor) _mi=$$((_mi + 1)); _pa=0;; \
  patch) _pa=$$((_pa + 1));; \
  *) echo "ERROR: unknown bump level '$$LEVEL'." >&2; exit 1;; \
esac; \
_new="$$_ma.$$_mi.$$_pa"; \
if git rev-parse -q --verify "refs/tags/v$$_new" >/dev/null; then \
  echo "ERROR: tag v$$_new already exists." >&2; exit 1; \
fi; \
echo "=== RELEASE $$LEVEL: $$(cat VERSION) -> $$_new ==="; \
printf '%s\n' "$$_new" > VERSION; \
awk -v ver="$$_new" -v day="$$(date +%F)" 'BEGIN{d=0} /^## \[Unreleased\]/ && !d {print; print ""; print "### Added"; print ""; print "### Changed"; print ""; print "### Fixed"; print ""; print "## [" ver "] - " day; d=1; next} {print}' CHANGELOG.md > CHANGELOG.md.tmp; \
mv CHANGELOG.md.tmp CHANGELOG.md; \
git add VERSION CHANGELOG.md; \
git commit -q -m "release: v$$_new"; \
$(RELEASE_TAG_BODY)
endef

.PHONY: help
help:
	@echo "Release:"
	@echo "  version           Show the current VERSION and release tag"
	@echo "  release-check     Preflight only. Changes nothing"
	@echo "  release-patch     Bump PATCH, roll changelog, commit, tag. Local only"
	@echo "  release-minor     Bump MINOR, roll changelog, commit, tag. Local only"
	@echo "  release-major     Bump MAJOR, roll changelog, commit, tag. Local only"
	@echo "  release-tag       Tag the current VERSION without bumping"
	@echo "  release-push      Push main + the tag. Fires release.yml. Not undoable"

.PHONY: version
version:
	@echo "VERSION file : $(VERSION)"
	@echo "Release tag  : $(RELEASE_TAG)"
	@echo "Latest tag   : $$(git describe --tags --abbrev=0 2>/dev/null || echo '(none yet)')"
	@_pub=$$(gh release view --json tagName -q .tagName 2>/dev/null \
	         || echo '(none)'); \
	 echo "Published    : $$_pub"

.PHONY: release-check
release-check:
	@$(RELEASE_PRECHECK); \
	 $(RELEASE_REQUIRE_UNRELEASED); \
	 IFS=. read -r _ma _mi _pa < VERSION; \
	 echo ""; \
	 echo "  current        v$$_ma.$$_mi.$$_pa"; \
	 echo "  release-patch  v$$_ma.$$_mi.$$((_pa + 1))   docs, dotfile" \
	      "tweaks, no tool changes"; \
	 echo "  release-minor  v$$_ma.$$((_mi + 1)).0   added tools or" \
	      "dotfiles"; \
	 echo "  release-major  v$$((_ma + 1)).0.0   removed/renamed tools" \
	      "or a base image change"

# The three release targets. Each bumps VERSION, rolls the changelog, commits
# and creates the annotated tag -- all LOCALLY. `make release-push` is the
# separate, deliberate step that publishes.
.PHONY: release-patch
release-patch:
	@LEVEL=patch; $(RELEASE_BUMP)

.PHONY: release-minor
release-minor:
	@LEVEL=minor; $(RELEASE_BUMP)

.PHONY: release-major
release-major:
	@LEVEL=major; $(RELEASE_BUMP)

# Tag the CURRENT VERSION without bumping it.
#
# An escape hatch, not part of the normal recipe: it only helps when a bump
# committed cleanly but the tag was lost or deleted before it was pushed.
# Requires the changelog to already carry a section for this version, so it
# cannot mint a tag with no release notes behind it -- which also means it
# cannot be used to cut a NEW release ([Unreleased] carries no version
# heading). Use release-<level> for that.
.PHONY: release-tag
release-tag:
	@$(RELEASE_PRECHECK); \
	 _v=$$(cat VERSION); \
	 if ! grep -q "^## \[$$_v\]" CHANGELOG.md; then \
	   echo "ERROR: CHANGELOG.md has no [$$_v] section. Add one, or use release-<level>." >&2; \
	   exit 1; \
	 fi; \
	 $(RELEASE_TAG_BODY)

# Publishes the commit and the tag. This is the only release target that
# talks to the network, and the only one that is not undoable -- a pushed
# tag is never moved.
#
# The tag push fires release.yml, which validates the tag against VERSION
# and CHANGELOG.md and creates the GitHub Release. Pushing the tag IS
# publishing -- there is no separate confirmation step after this one.
#
# `git push origin main` comes FIRST and is load-bearing. The release commit
# was made locally on main, so the branch must reach origin before the tag
# does -- push the tag alone and the tag names a commit nobody else can see.
# Both pushes go in one target so the ordering cannot be got wrong by hand.
.PHONY: release-push
release-push:
	@_tag="$(RELEASE_TAG)"; \
	 if ! git rev-parse -q --verify "refs/tags/$$_tag" >/dev/null; then \
	   echo "ERROR: no local tag $$_tag. Run 'make release-<level>' first." >&2; exit 1; \
	 fi; \
	 echo "=== PUSH $$_tag ==="; \
	 git push origin main; \
	 git push origin "$$_tag"; \
	 echo "  pushed. release.yml is now publishing $$_tag:"; \
	 echo "    gh run list --workflow=release.yml"
